services:
  core-simulator:
    image: unfoldedcircle/core-simulator
    container_name: core-simulator
    restart: "unless-stopped"
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - UC_TOKEN_PATH=/tmp/ui-env/ws-token
#      - UC_MODEL=UCR3
#      - UC_INTEGRATION_DISABLE_CERT_VERIFICATION=true
# To run the simulator on the same network as the host. Existing Docker integrations must be reconfigured!
#    network_mode: "host"
    volumes:
      - simulator-data:/data
      - ./ui-env:/tmp/ui-env
      - ./upload:/data/upload
      # If you have a Pro license of Font Awesome 6, you can put the font files into the ./fontawesome6 directory
      # and uncomment the following volume mapping.
      # Required: fa-thin-100.woff2 & .ttf, fa-light-300.woff2 & .ttf, fa-regular-400.woff2 & .ttf
      #- ./fontawesome6:/app/webroot/configurator/fonts/fontawesome6

  integration-hass:
    image: unfoldedcircle/integration-hass
    container_name: integration-hass
    restart: "unless-stopped"
    # configure Home Assistant demo server defined below
    environment:
      - UC_HASS_URL=ws://hassio:8123/api/websocket
      - UC_HASS_TOKEN=${HASS_TOKEN}
      # Token can also be propagated from an already defined environment variable. E.g. if defined in HASS_TOKEN:
      #- UC_HASS_TOKEN=$HASS_TOKEN
    # Port exposure is not really required, only for testing
    ports:
      - "8000:8000"
    volumes:
      - ./integration-hass:/config

  hassio:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant-demo
    hostname: hassio
    restart: "unless-stopped"
    environment:
      - TZ=Europe/Zurich
    # expose web ui
    ports:
      - "8123:8123"
    volumes:
      - ./hass_config:/config
    privileged: true

  # Optional local speech-to-text system for Home Assistant. Can be disabled if not used.
  speech-to-phrase:
    image: rhasspy/wyoming-speech-to-phrase
    container_name: speech-to-phrase
    restart: unless-stopped
    # Port exposure is not really required, only for testing
    ports:
      - "10300:10300"
    volumes:
      - ./speech-to-phrase/models:/models
      - ./speech-to-phrase/train:/train
    command:
      --hass-websocket-uri 'ws://hassio:8123/api/websocket'
      --hass-token ${HASS_TOKEN}
      --retrain-on-start

# Python integration library example
#  python-example:
#    build: python-intg-example
#    container_name: python-example
#    hostname: python-example

volumes:
  simulator-data:
